### PR TITLE
Update CNAME

### PR DESCRIPTION
**Pull request by waleburg**

### CODE REVIEW

**Review by leandrolerena — CHANGES_REQUESTED** [review]
Das CNAME muss noch auf unserem DNS gesetzt werden

Navigate to your DNS provider and create a CNAME record that points your subdomain to the default domain for your site. For example, if you want to use the subdomain www.example.com for your user site, create a CNAME record that points www.example.com to <user>.github.io. If you want to use the subdomain www.anotherexample.com for your organization site, create a CNAME record that points www.anotherexample.com to <organization>.github.io. The CNAME record should always point to <user>.github.io or <organization>.github.io, excluding the repository name. For more information about how to create the correct record, see your DNS provider's documentation. For more information about the default domain for your site, see "About GitHub Pages."


More Info: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by leandrolerena** [comment]
@waleburg schaust Du? Bzw, soll das schon jetzt gemacht werden?

**Comment by hwuethrich** [comment]
Btw, für die Hauptdomain (Apex-Domain) braucht es `A` records: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

**Comment by hwuethrich** [comment]
Habs eingetragen

**Comment by hwuethrich** [comment]
Screenshot 2021-05-31 at 16 18 03

**Review by leandrolerena — APPROVED** [review]

**Pull request merged**
